version: "3.8"
services:
  auth-server:
    image: zhoozhoo/spring-cloud-auth-server:0.2.0-SNAPSHOT
    container_name: auth-server
    ports:
      - 8180:8080

  config-server:
    image: zhoozhoo/spring-cloud-config-server:0.2.0-SNAPSHOT
    container_name: config-server
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-I", "http://config-server:8888"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 8888:8888

  discovery-server:
    image: zhoozhoo/spring-cloud-discovery-server:0.2.0-SNAPSHOT
    container_name: discovery-server
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://discovery-server:8761"]
      interval: 5s
      timeout: 3s
      retries: 10
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761

  guest-service:
    image: zhoozhoo/spring-cloud-guest-service:0.2.0-SNAPSHOT
    container_name: guest-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 8081:8081

  reservation-service:
    image: zhoozhoo/spring-cloud-reservation-service:0.2.0-SNAPSHOT
    container_name: reservation-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 8082:8082

  room-service:
    image: zhoozhoo/spring-cloud-room-service:0.2.0-SNAPSHOT
    container_name: room-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 8083:8083

  room-reservation-service:
    image: zhoozhoo/spring-cloud-room-reservation-service:0.2.0-SNAPSHOT
    container_name: room-reservation-service
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 8084:8084

  api-gateway:
    image: zhoozhoo/spring-cloud-api-gateway:0.2.0-SNAPSHOT
    container_name: api-gateway
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
      - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    deploy:
      resources:
        limits:
          memory: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411
     
  admin-server:
    image: zhoozhoo/spring-cloud-admin-server:0.2.0-SNAPSHOT
    container_name: admin-server
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      config-server:
        condition: service_healthy
      discovery-server:
        condition: service_healthy
    ports:
     - 9090:9090
