spring:
  application:
    name: auth-server
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
