spring:
  application:
    name: guest-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    config:
      discovery: 
        enabled: true
        serviceId: config-server
      fail-fast: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761}/eureka/
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
