server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhoozhoo/spring-cloud-examples-config
          default-label: master
        native:
          searchLocations: file:///${GIT_REPO}

