server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/zhoozhoo/spring-cloud-examples-config.git
          force-pull: true

