name: Build
on:
  pull_request:
    branches:
      - master
      
build:
  runs-on: [ubuntu-latest]

  - name: check out branch
    uses: actions/checkout@v3

  - name: Set up JDK 21
    uses: actions/setup-java@v3
    with:
      java-version: '21'
      distribution: 'temurin'
      cache: maven

  - name: compile the project
    run: mvn compile

  - name: run test case
    run: mvn test
