name: Build
on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: compile the project
        run: mvn compile

      - name: run test case
        run: mvn test
