name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
      
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
  
      - name: compile the project
        run: mvn compile

      - name: run test case
        run: mvn test
